## randomly split rows into training and test data set

In [1]:
import numpy as np

In [2]:
team=np.arange(1, 11)
team

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.random.shuffle(team)
team

array([ 5,  2,  9,  6,  4,  1,  7, 10,  8,  3])

In [4]:
training, test=team[:7], team[7:]
print(training)
print(test)

[5 2 9 6 4 1 7]
[10  8  3]


### method 1: shuffle rows -> slice

In [5]:
d=np.random.randint(100, 400, size=(10, 4))
d

array([[257, 218, 319, 231],
       [353, 325, 397, 394],
       [108, 256, 293, 252],
       [104, 144, 141, 265],
       [195, 387, 169, 248],
       [285, 347, 119, 237],
       [330, 243, 153, 321],
       [169, 365, 309, 332],
       [383, 108, 109, 329],
       [188, 102, 197, 132]])

In [6]:
np.random.shuffle(d)
d

array([[285, 347, 119, 237],
       [330, 243, 153, 321],
       [104, 144, 141, 265],
       [383, 108, 109, 329],
       [195, 387, 169, 248],
       [188, 102, 197, 132],
       [257, 218, 319, 231],
       [169, 365, 309, 332],
       [108, 256, 293, 252],
       [353, 325, 397, 394]])

In [7]:
# training (70% or 7 rows or row 0 to 6), test (30% or 3 rows or row 7 to 9)
training, test = d[:7], d[7:]

In [8]:
training

array([[285, 347, 119, 237],
       [330, 243, 153, 321],
       [104, 144, 141, 265],
       [383, 108, 109, 329],
       [195, 387, 169, 248],
       [188, 102, 197, 132],
       [257, 218, 319, 231]])

In [9]:
test

array([[169, 365, 309, 332],
       [108, 256, 293, 252],
       [353, 325, 397, 394]])

### method 2: random choice (n rows)

In [10]:
d=np.random.randint(100, 400, size=(10, 4))
d

array([[106, 101, 282, 349],
       [187, 232, 255, 368],
       [341, 372, 246, 215],
       [312, 136, 250, 109],
       [257, 136, 281, 103],
       [394, 223, 326, 147],
       [249, 249, 365, 378],
       [182, 123, 318, 126],
       [228, 355, 129, 264],
       [264, 367, 357, 293]])

In [11]:
# split 70:30
r1=np.random.choice(np.arange(d.shape[0]), size=7, replace=False)
r1

array([2, 3, 7, 6, 1, 9, 0])

In [12]:
training=d[r1] # training data set 70% or 7 rows
training

array([[341, 372, 246, 215],
       [312, 136, 250, 109],
       [182, 123, 318, 126],
       [249, 249, 365, 378],
       [187, 232, 255, 368],
       [264, 367, 357, 293],
       [106, 101, 282, 349]])

In [13]:
np.setdiff1d(np.arange(d.shape[0]), r1)

array([4, 5, 8])

In [14]:
test=d[np.setdiff1d(np.arange(d.shape[0]), r1)] # test data set 30% or 3 rows
test

array([[257, 136, 281, 103],
       [394, 223, 326, 147],
       [228, 355, 129, 264]])