In [2]:
import numpy as np
celcius=np.arange(0,101)

In [3]:
#far=cel*1.8+32
farenheit=celcius*1.8+32

In [4]:
t=np.stack((celcius,farenheit),axis=1)
t

array([[  0. ,  32. ],
       [  1. ,  33.8],
       [  2. ,  35.6],
       [  3. ,  37.4],
       [  4. ,  39.2],
       [  5. ,  41. ],
       [  6. ,  42.8],
       [  7. ,  44.6],
       [  8. ,  46.4],
       [  9. ,  48.2],
       [ 10. ,  50. ],
       [ 11. ,  51.8],
       [ 12. ,  53.6],
       [ 13. ,  55.4],
       [ 14. ,  57.2],
       [ 15. ,  59. ],
       [ 16. ,  60.8],
       [ 17. ,  62.6],
       [ 18. ,  64.4],
       [ 19. ,  66.2],
       [ 20. ,  68. ],
       [ 21. ,  69.8],
       [ 22. ,  71.6],
       [ 23. ,  73.4],
       [ 24. ,  75.2],
       [ 25. ,  77. ],
       [ 26. ,  78.8],
       [ 27. ,  80.6],
       [ 28. ,  82.4],
       [ 29. ,  84.2],
       [ 30. ,  86. ],
       [ 31. ,  87.8],
       [ 32. ,  89.6],
       [ 33. ,  91.4],
       [ 34. ,  93.2],
       [ 35. ,  95. ],
       [ 36. ,  96.8],
       [ 37. ,  98.6],
       [ 38. , 100.4],
       [ 39. , 102.2],
       [ 40. , 104. ],
       [ 41. , 105.8],
       [ 42. , 107.6],
       [ 43

In [5]:
np.savetxt('temperature.csv',t)

In [7]:
np.savetxt('temp2.csv',t,delimiter=',',fmt='%.1f')

In [8]:
np.savetxt('temp3.csv',t,
          delimiter=',',
          fmt='%.2f',
          header='celcious,farenheit')

In [9]:
np.savetxt('temp4.csv',t,
          delimiter=',',
          fmt='%.1f',
          header='celcius,farenheit',
          comments='')

In [10]:
#usd=[1,50]
#riel=usd*4100 
#stack save

## loadtxt ( load data from text file to numpy array)

In [14]:
s=np.loadtxt('temperature.csv')
s

array([[  0. ,  32. ],
       [  1. ,  33.8],
       [  2. ,  35.6],
       [  3. ,  37.4],
       [  4. ,  39.2],
       [  5. ,  41. ],
       [  6. ,  42.8],
       [  7. ,  44.6],
       [  8. ,  46.4],
       [  9. ,  48.2],
       [ 10. ,  50. ],
       [ 11. ,  51.8],
       [ 12. ,  53.6],
       [ 13. ,  55.4],
       [ 14. ,  57.2],
       [ 15. ,  59. ],
       [ 16. ,  60.8],
       [ 17. ,  62.6],
       [ 18. ,  64.4],
       [ 19. ,  66.2],
       [ 20. ,  68. ],
       [ 21. ,  69.8],
       [ 22. ,  71.6],
       [ 23. ,  73.4],
       [ 24. ,  75.2],
       [ 25. ,  77. ],
       [ 26. ,  78.8],
       [ 27. ,  80.6],
       [ 28. ,  82.4],
       [ 29. ,  84.2],
       [ 30. ,  86. ],
       [ 31. ,  87.8],
       [ 32. ,  89.6],
       [ 33. ,  91.4],
       [ 34. ,  93.2],
       [ 35. ,  95. ],
       [ 36. ,  96.8],
       [ 37. ,  98.6],
       [ 38. , 100.4],
       [ 39. , 102.2],
       [ 40. , 104. ],
       [ 41. , 105.8],
       [ 42. , 107.6],
       [ 43

In [17]:
s2=np.loadtxt('temp2.csv',delimiter=',')
s2

array([[  0. ,  32. ],
       [  1. ,  33.8],
       [  2. ,  35.6],
       [  3. ,  37.4],
       [  4. ,  39.2],
       [  5. ,  41. ],
       [  6. ,  42.8],
       [  7. ,  44.6],
       [  8. ,  46.4],
       [  9. ,  48.2],
       [ 10. ,  50. ],
       [ 11. ,  51.8],
       [ 12. ,  53.6],
       [ 13. ,  55.4],
       [ 14. ,  57.2],
       [ 15. ,  59. ],
       [ 16. ,  60.8],
       [ 17. ,  62.6],
       [ 18. ,  64.4],
       [ 19. ,  66.2],
       [ 20. ,  68. ],
       [ 21. ,  69.8],
       [ 22. ,  71.6],
       [ 23. ,  73.4],
       [ 24. ,  75.2],
       [ 25. ,  77. ],
       [ 26. ,  78.8],
       [ 27. ,  80.6],
       [ 28. ,  82.4],
       [ 29. ,  84.2],
       [ 30. ,  86. ],
       [ 31. ,  87.8],
       [ 32. ,  89.6],
       [ 33. ,  91.4],
       [ 34. ,  93.2],
       [ 35. ,  95. ],
       [ 36. ,  96.8],
       [ 37. ,  98.6],
       [ 38. , 100.4],
       [ 39. , 102.2],
       [ 40. , 104. ],
       [ 41. , 105.8],
       [ 42. , 107.6],
       [ 43

In [20]:
s3=np.loadtxt('temp3.csv',delimiter=',',skiprows=1)
s3

array([[  0. ,  32. ],
       [  1. ,  33.8],
       [  2. ,  35.6],
       [  3. ,  37.4],
       [  4. ,  39.2],
       [  5. ,  41. ],
       [  6. ,  42.8],
       [  7. ,  44.6],
       [  8. ,  46.4],
       [  9. ,  48.2],
       [ 10. ,  50. ],
       [ 11. ,  51.8],
       [ 12. ,  53.6],
       [ 13. ,  55.4],
       [ 14. ,  57.2],
       [ 15. ,  59. ],
       [ 16. ,  60.8],
       [ 17. ,  62.6],
       [ 18. ,  64.4],
       [ 19. ,  66.2],
       [ 20. ,  68. ],
       [ 21. ,  69.8],
       [ 22. ,  71.6],
       [ 23. ,  73.4],
       [ 24. ,  75.2],
       [ 25. ,  77. ],
       [ 26. ,  78.8],
       [ 27. ,  80.6],
       [ 28. ,  82.4],
       [ 29. ,  84.2],
       [ 30. ,  86. ],
       [ 31. ,  87.8],
       [ 32. ,  89.6],
       [ 33. ,  91.4],
       [ 34. ,  93.2],
       [ 35. ,  95. ],
       [ 36. ,  96.8],
       [ 37. ,  98.6],
       [ 38. , 100.4],
       [ 39. , 102.2],
       [ 40. , 104. ],
       [ 41. , 105.8],
       [ 42. , 107.6],
       [ 43

In [24]:
s4=np.loadtxt('temp4.csv',delimiter= ',',skiprows=1)#skiprows
s4

array([[  0. ,  32. ],
       [  1. ,  33.8],
       [  2. ,  35.6],
       [  3. ,  37.4],
       [  4. ,  39.2],
       [  5. ,  41. ],
       [  6. ,  42.8],
       [  7. ,  44.6],
       [  8. ,  46.4],
       [  9. ,  48.2],
       [ 10. ,  50. ],
       [ 11. ,  51.8],
       [ 12. ,  53.6],
       [ 13. ,  55.4],
       [ 14. ,  57.2],
       [ 15. ,  59. ],
       [ 16. ,  60.8],
       [ 17. ,  62.6],
       [ 18. ,  64.4],
       [ 19. ,  66.2],
       [ 20. ,  68. ],
       [ 21. ,  69.8],
       [ 22. ,  71.6],
       [ 23. ,  73.4],
       [ 24. ,  75.2],
       [ 25. ,  77. ],
       [ 26. ,  78.8],
       [ 27. ,  80.6],
       [ 28. ,  82.4],
       [ 29. ,  84.2],
       [ 30. ,  86. ],
       [ 31. ,  87.8],
       [ 32. ,  89.6],
       [ 33. ,  91.4],
       [ 34. ,  93.2],
       [ 35. ,  95. ],
       [ 36. ,  96.8],
       [ 37. ,  98.6],
       [ 38. , 100.4],
       [ 39. , 102.2],
       [ 40. , 104. ],
       [ 41. , 105.8],
       [ 42. , 107.6],
       [ 43