### savetxt (save ndarray to text file)
### loadtxt (load data from text file to numpy array) 

In [1]:
import numpy as np

In [3]:
#array range (0 ==>100) celciuos 
#fah =cel*(9/5)+32  
cel=np.arange(101)
cel

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [4]:
fah=cel*(9/5)+32
fah

array([ 32. ,  33.8,  35.6,  37.4,  39.2,  41. ,  42.8,  44.6,  46.4,
        48.2,  50. ,  51.8,  53.6,  55.4,  57.2,  59. ,  60.8,  62.6,
        64.4,  66.2,  68. ,  69.8,  71.6,  73.4,  75.2,  77. ,  78.8,
        80.6,  82.4,  84.2,  86. ,  87.8,  89.6,  91.4,  93.2,  95. ,
        96.8,  98.6, 100.4, 102.2, 104. , 105.8, 107.6, 109.4, 111.2,
       113. , 114.8, 116.6, 118.4, 120.2, 122. , 123.8, 125.6, 127.4,
       129.2, 131. , 132.8, 134.6, 136.4, 138.2, 140. , 141.8, 143.6,
       145.4, 147.2, 149. , 150.8, 152.6, 154.4, 156.2, 158. , 159.8,
       161.6, 163.4, 165.2, 167. , 168.8, 170.6, 172.4, 174.2, 176. ,
       177.8, 179.6, 181.4, 183.2, 185. , 186.8, 188.6, 190.4, 192.2,
       194. , 195.8, 197.6, 199.4, 201.2, 203. , 204.8, 206.6, 208.4,
       210.2, 212. ])

In [9]:
a=np.stack((cel,fah),axis=1)
a

array([[  0. ,  32. ],
       [  1. ,  33.8],
       [  2. ,  35.6],
       [  3. ,  37.4],
       [  4. ,  39.2],
       [  5. ,  41. ],
       [  6. ,  42.8],
       [  7. ,  44.6],
       [  8. ,  46.4],
       [  9. ,  48.2],
       [ 10. ,  50. ],
       [ 11. ,  51.8],
       [ 12. ,  53.6],
       [ 13. ,  55.4],
       [ 14. ,  57.2],
       [ 15. ,  59. ],
       [ 16. ,  60.8],
       [ 17. ,  62.6],
       [ 18. ,  64.4],
       [ 19. ,  66.2],
       [ 20. ,  68. ],
       [ 21. ,  69.8],
       [ 22. ,  71.6],
       [ 23. ,  73.4],
       [ 24. ,  75.2],
       [ 25. ,  77. ],
       [ 26. ,  78.8],
       [ 27. ,  80.6],
       [ 28. ,  82.4],
       [ 29. ,  84.2],
       [ 30. ,  86. ],
       [ 31. ,  87.8],
       [ 32. ,  89.6],
       [ 33. ,  91.4],
       [ 34. ,  93.2],
       [ 35. ,  95. ],
       [ 36. ,  96.8],
       [ 37. ,  98.6],
       [ 38. , 100.4],
       [ 39. , 102.2],
       [ 40. , 104. ],
       [ 41. , 105.8],
       [ 42. , 107.6],
       [ 43

In [10]:
#csv 
np.savetxt('temperature.csv',a)

In [13]:
np.savetxt('tem2.csv',a,
          delimiter=',',
          fmt='%.1f',
          header='celious,fahranheit')

In [14]:
np.savetxt('tem3.csv',a,
          delimiter=',',
          fmt='%.1f',
          header='celious,fahranheit',
          comments=' ')

### load file

In [4]:
import numpy as np
r=np.loadtxt('temperature.csv')
r

array([[  0. ,  32. ],
       [  1. ,  33.8],
       [  2. ,  35.6],
       [  3. ,  37.4],
       [  4. ,  39.2],
       [  5. ,  41. ],
       [  6. ,  42.8],
       [  7. ,  44.6],
       [  8. ,  46.4],
       [  9. ,  48.2],
       [ 10. ,  50. ],
       [ 11. ,  51.8],
       [ 12. ,  53.6],
       [ 13. ,  55.4],
       [ 14. ,  57.2],
       [ 15. ,  59. ],
       [ 16. ,  60.8],
       [ 17. ,  62.6],
       [ 18. ,  64.4],
       [ 19. ,  66.2],
       [ 20. ,  68. ],
       [ 21. ,  69.8],
       [ 22. ,  71.6],
       [ 23. ,  73.4],
       [ 24. ,  75.2],
       [ 25. ,  77. ],
       [ 26. ,  78.8],
       [ 27. ,  80.6],
       [ 28. ,  82.4],
       [ 29. ,  84.2],
       [ 30. ,  86. ],
       [ 31. ,  87.8],
       [ 32. ,  89.6],
       [ 33. ,  91.4],
       [ 34. ,  93.2],
       [ 35. ,  95. ],
       [ 36. ,  96.8],
       [ 37. ,  98.6],
       [ 38. , 100.4],
       [ 39. , 102.2],
       [ 40. , 104. ],
       [ 41. , 105.8],
       [ 42. , 107.6],
       [ 43

In [6]:
r2=np.loadtxt('tem2.csv', delimiter=',')
r2

array([[  0. ,  32. ],
       [  1. ,  33.8],
       [  2. ,  35.6],
       [  3. ,  37.4],
       [  4. ,  39.2],
       [  5. ,  41. ],
       [  6. ,  42.8],
       [  7. ,  44.6],
       [  8. ,  46.4],
       [  9. ,  48.2],
       [ 10. ,  50. ],
       [ 11. ,  51.8],
       [ 12. ,  53.6],
       [ 13. ,  55.4],
       [ 14. ,  57.2],
       [ 15. ,  59. ],
       [ 16. ,  60.8],
       [ 17. ,  62.6],
       [ 18. ,  64.4],
       [ 19. ,  66.2],
       [ 20. ,  68. ],
       [ 21. ,  69.8],
       [ 22. ,  71.6],
       [ 23. ,  73.4],
       [ 24. ,  75.2],
       [ 25. ,  77. ],
       [ 26. ,  78.8],
       [ 27. ,  80.6],
       [ 28. ,  82.4],
       [ 29. ,  84.2],
       [ 30. ,  86. ],
       [ 31. ,  87.8],
       [ 32. ,  89.6],
       [ 33. ,  91.4],
       [ 34. ,  93.2],
       [ 35. ,  95. ],
       [ 36. ,  96.8],
       [ 37. ,  98.6],
       [ 38. , 100.4],
       [ 39. , 102.2],
       [ 40. , 104. ],
       [ 41. , 105.8],
       [ 42. , 107.6],
       [ 43

In [8]:
r3=np.loadtxt('tem3.csv', delimiter=',',skiprows=1)
r3

array([[  0. ,  32. ],
       [  1. ,  33.8],
       [  2. ,  35.6],
       [  3. ,  37.4],
       [  4. ,  39.2],
       [  5. ,  41. ],
       [  6. ,  42.8],
       [  7. ,  44.6],
       [  8. ,  46.4],
       [  9. ,  48.2],
       [ 10. ,  50. ],
       [ 11. ,  51.8],
       [ 12. ,  53.6],
       [ 13. ,  55.4],
       [ 14. ,  57.2],
       [ 15. ,  59. ],
       [ 16. ,  60.8],
       [ 17. ,  62.6],
       [ 18. ,  64.4],
       [ 19. ,  66.2],
       [ 20. ,  68. ],
       [ 21. ,  69.8],
       [ 22. ,  71.6],
       [ 23. ,  73.4],
       [ 24. ,  75.2],
       [ 25. ,  77. ],
       [ 26. ,  78.8],
       [ 27. ,  80.6],
       [ 28. ,  82.4],
       [ 29. ,  84.2],
       [ 30. ,  86. ],
       [ 31. ,  87.8],
       [ 32. ,  89.6],
       [ 33. ,  91.4],
       [ 34. ,  93.2],
       [ 35. ,  95. ],
       [ 36. ,  96.8],
       [ 37. ,  98.6],
       [ 38. , 100.4],
       [ 39. , 102.2],
       [ 40. , 104. ],
       [ 41. , 105.8],
       [ 42. , 107.6],
       [ 43