In [7]:
import numpy as np
print(f'Version ={np.__version__}')

Version =1.18.5


In [2]:
a=np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
b=np.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
c=np.array([1,2,3,4,5,6,7,8,9])

In [10]:
c.size

9

In [11]:
b.size

9

In [12]:
c.shape

(9,)

In [13]:
b.shape

(3, 3)

In [14]:
np.min(c)

1

In [15]:
np.max(b)

9

In [16]:
np.sum(b)

45

In [17]:
# mean vs median 
# 1 5 8 3 4 6 10 
#mean (average) = sum/number 
#median (1 3 4 5 6 8 10)
e=np.array([1,5,8,3,4,6,10])
np.mean(e)

5.285714285714286

In [18]:
np.median(e)

5.0

In [ ]:
 f=np.array([45,67,89,90,123,456,703,210])
#1. find min, max and sum 
#2. Find mean 
#3. Find median 
#4. reshape(2x4)
f.reshape(2,4)

In [ ]:
### mean, median vs mode() (scipy)
### boolean array vs boolean indexing 
### iterate numpy 
re